const genres = [
    "Science Fiction",
    "Fantasy",
    "Mystery/Thriller",
    "Historical Fiction",
    "Dystopian",
    "Adventure",
    "Romance",
    "Horror",
    "Comedy",
    "Slice of Life",
    "Superhero",
    "Post-Apocalyptic",
    "Cyberpunk",
    "Fairytale Retelling",
    "Space Opera",
    "Steampunk",
    "Alternate History",
    "Time Travel",
    "Magical Realism",
    "Spy",
    "War",
    "Western",
    "Urban Fantasy",
    "Paranormal",
    "Young Adult",
    "Coming of Age",
    "Drama",
    "Biopunk",
    "Legal Thriller",
    "Military Fiction",
    "Political Intrigue",
    "Mythological",
    "Survival",
    "Conspiracy",
    "Wuxia",
    "Apocalyptic",
    "Heist",
    "Gothic",
    "Medical Drama",
    "Fairy Punk",
]

export {genres}